[package]
name = "rdf_graph_converter"
version = "0.1.0"
edition = "2021"

[dependencies]
oxrdfio = "0.1.4"
oxrdf = "0.2.3"
csv = "1.3.1"
clap = { version = "4.5.23", features = ["derive"] }
serde_json = "1.0.134"
